### ISSUE TITLE
Tenon API Key

### ISSUE THREAD

**Issue by brothman01** [joedolson/access-monitor#1]
The 'You must enter a Tenon API key to use Access Monitor.' with a link in it is broken on both the plugins page and the settings' page header.

I am using a local valet dev site, not sure if that has any bearing on this or not.

**Comment by brothman01** [comment]
I also got an API key from the tenon site and I entered it on the plugin settings page but when I pressed 'Update Settings' WordPress throws an error and says "Sorry, you are not allowed to access this page.".

**Comment by joedolson** [comment]
It could. Can you tell me what the actual URL in that link is?

**Comment by brothman01** [comment]
sure,
1) the error in WP_DEBUG is "Notice: Undefined index: tenon_api_key in .../valet/test-site/wp-content/plugins/access-monitor-master/access-monitor.php"

2) The URL linked to when I press the "enter a Tenon API Key" at the top is 'http://test-site.dev/wp-admin/edit.php?post_type=tenon-report&page=access-monitor/access-monitor.php#settings'

3) The URL that tries to open but kills the site when I press the "Update Settings" button is 'http://test-site.dev/wp-admin/edit.php?post_type=tenon-report&page=access-monitor/access-monitor.php'

**Comment by joedolson** [comment]
So, #2 and 3 are the same URL, except for the identifier. Is it *only* the latter URL that throws the error?

I'm aware of that notice; but thanks for mentioning it. 

Is there anything about either URL that is clearly wrong for you? E.g., that's not the correct domain, that's not where your wp-admin directory is located, etc. The rest of it is fine.

**Comment by brothman01** [comment]
>  Is it only the latter URL that throws the error?

No, both urls open a wp_die() page that says "Sorry, you are not allowed to access this page."

> Is there anything about either URL that is clearly wrong for you?

Nope, the beginning of the url looks fine.  I know the domain looks weird, but it is a valet install so .dev is correct.

**Comment by joedolson** [comment]
OK. Are you able to visit the settings page in any way, or is it *just* these links that don't work? If you are able to visit the settings page, what is the URL for that page? If not, does your user role have the 'manage_options' capability?

**Comment by brothman01** [comment]
> Are you able to visit the settings page in any way ... If you are able to visit the settings page, what is the URL for that page?

Yes I can visit the settings page and the URL is 'http://test-site.dev/wp-admin/edit.php?post_type=tenon-report&page=access-monitor-master%2Faccess-monitor.php'


> If not, does your user role have the 'manage_options' capability?

I am able to visit the settings page, but yes the account does have the 'manage_option' capability and is an administrator.

**Comment by joedolson** [comment]
OK. You have Access Monitor installed in a directory named 'access-monitor-master'. Rename that directory to 'access-monitor'.

**Comment by brothman01** [comment]
nice! that did it, awesome, thanks.
